### ISSUE TITLE
share no work :(

### ISSUE THREAD

**Issue by Kowarii** [circle67/MyWordle#1]
bugh

**Comment by circle67** [comment]
Just generated:

> MyWordle 6/6
> ⬛🟨⬛🟨⬛
> ⬛🟨⬛🟨⬛
> 🟨🟩🟨🟨⬛
> 🟨🟨🟩🟨⬛
> ⬛🟩🟩🟩🟩
> 🟩🟩🟩🟩🟩

It seems to work; it may be because you lost, in which case you cannot share anything.
